networks:
    diytaskmanager-network:
        driver: bridge

volumes:
    diytaskmanager-postgresql-data:
        driver: local

services:
    dashboard:
        image: cdray527/diytaskmanager:dev
        build:
            context: ../
            dockerfile: apps/frontend/dashboard/Dockerfile
            target: development
        container_name: diytaskmanager-dashboard
        environment:
            - NODE_ENV=development
        ports:
            - '4000:4000'
        volumes:
            - ../:/app
            - /app/node_modules
        networks:
            - diytaskmanager-network
        command: ['npm', 'run', 'dev:dashboard']
    api:
        image: cdray527/diytaskmanager:dev
        build:
            context: ../
            dockerfile: apps/backend/api/Dockerfile
            target: development
        container_name: diytaskmanager-api
        environment:
            - NODE_ENV=development
        ports:
            - '3000:3000'
        volumes:
            - ../:/app
            - /app/node_modules
        networks:
            - diytaskmanager-network
        command: ['npm', 'run', 'dev:api']
