networks:
    diytaskmanager-network:
        driver: bridge

volumes:
    diytaskmanager-postgresql-data:
        driver: local
    # diytaskmanager-node-modules:
    #     driver: local

services:
    diytaskmanager-dashboard:
        build:
            context: ../
            dockerfile: apps/frontend/dashboard/Dockerfile
            target: development
        container_name: diytaskmanager-dashboard
        depends_on:
            - diytaskmanager-api
        environment:
            - NODE_ENV=development
            - NEXT_PRIVATE_TASK_API_URL=http://diytaskmanager-api:3000
            - NEXT_PUBLIC_TASK_API_URL=http://localhost:3000
        ports:
            - '4000:4000'
        volumes:
            - ../:/app
            - /app/node_modules
        networks:
            - diytaskmanager-network
        command: ['npm', 'run', 'dev:dashboard']
    diytaskmanager-api:
        build:
            context: ../
            dockerfile: apps/backend/api/Dockerfile
            target: development
        container_name: diytaskmanager-api
        depends_on:
            diytaskmanager-postgresql:
                condition: service_healthy
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://diytaskmanagerdev:diytaskmanagerdevpw@diytaskmanager-postgresql:5432/diytaskmanager-db
        ports:
            - '3000:3000'
            - '5555:5555'
        volumes:
            - ../:/app
            - /app/node_modules
        networks:
            - diytaskmanager-network
        command: ['sh', '-c', 'npx prisma generate && npm run dev:api']
    diytaskmanager-postgresql:
        image: postgres:16
        container_name: diytaskmanager-postgresql
        environment:
            - POSTGRES_USER=diytaskmanagerdev
            - POSTGRES_PASSWORD=diytaskmanagerdevpw
            - POSTGRES_DB=diytaskmanager-db
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U diytaskmanagerdev']
            interval: 5s
            timeout: 2s
            retries: 20
        volumes:
            - diytaskmanager-postgresql-data:/var/lib/postgresql/data/
        networks:
            - diytaskmanager-network
